"""
Generates static 32x32 PNG sprites for the combat-gear pickup icons that
previously shipped as 8x8 codex placeholders, plus the bow and crossbow
(previously generated by gen_ranged_assets.py).

Covers:
  bronze_sword, leather_armor, leather_helmet, leather_legs,
  traveler_boots, wooden_shield, bow, crossbow

Each object gets a single `sprite.png` in its overworld_objects directory.
Style matches gen_gathering_sprites.py and gen_casting_item_sprites.py —
chunky pixels, 2-3 shading levels per material, no anti-aliasing, transparent
background, small ground shadow under each item.
"""

from __future__ import annotations

import os
from PIL import Image

W, H = 32, 32
BG = (0, 0, 0, 0)
SHADOW = (0, 0, 0, 70)


def new_img() -> Image.Image:
    return Image.new("RGBA", (W, H), BG)


def helpers(img: Image.Image):
    def px(x: int, y: int, c):
        if 0 <= x < W and 0 <= y < H:
            img.putpixel((x, y), c)

    def rect(x: int, y: int, w: int, h: int, c):
        for dy in range(h):
            for dx in range(w):
                px(x + dx, y + dy, c)

    return px, rect


def ground_shadow(rect, cx: int, cy: int, half: int) -> None:
    rect(cx - half, cy, half * 2 + 1, 1, SHADOW)
    inner = max(half - 2, 1)
    rect(cx - inner, cy + 1, inner * 2 + 1, 1, SHADOW)


# ---------- weapons ---------- #


def make_bronze_sword() -> Image.Image:
    """Diagonal sword from lower-left grip to upper-right tip. Leather-wrapped
    grip, brass crossguard, long bronze blade with a steel-tinted edge."""
    img = new_img()
    px, rect = helpers(img)
    ground_shadow(rect, 16, 27, 8)

    grip_dark = (50, 30, 15, 255)
    grip = (110, 70, 35, 255)
    grip_hi = (160, 110, 65, 255)
    pommel_dark = (55, 35, 20, 255)
    pommel = (180, 145, 70, 255)
    pommel_hi = (230, 200, 110, 255)
    guard_dark = (130, 90, 30, 255)
    guard = (215, 165, 70, 255)
    guard_hi = (245, 215, 130, 255)

    bronze_dark = (115, 75, 35, 255)
    bronze = (190, 135, 65, 255)
    bronze_hi = (240, 200, 130, 255)
    edge = (255, 240, 200, 255)

    # Pommel (round cap at the butt of the grip)
    px(5, 26, pommel_dark)
    px(6, 26, pommel)
    px(6, 27, pommel_dark)
    px(7, 26, pommel_hi)
    px(7, 27, pommel)

    # Grip (diagonal leather wrap, 5 steps)
    grip_pts = [(7, 25), (8, 24), (9, 23), (10, 22), (11, 21)]
    for (x, y) in grip_pts:
        px(x, y, grip)
        px(x - 1, y, grip_dark)
        px(x, y + 1, grip_dark)
        px(x + 1, y, grip_hi)
    # Wrap stripes (alternating darker bands)
    px(7, 24, grip_dark)
    px(9, 22, grip_dark)

    # Crossguard — short bar perpendicular to the blade at (11, 21)
    # Goes from (9, 23) up-right to (13, 19) — opposite diagonal
    guard_pts = [(9, 23), (10, 22), (11, 21), (12, 20), (13, 19)]
    for (x, y) in guard_pts:
        px(x, y, guard)
    # Highlight on the upper side of the guard
    px(10, 22, guard_hi)
    px(11, 21, guard_hi)
    px(12, 20, guard_hi)
    # Shadow on the lower side
    px(9, 24, guard_dark)
    px(13, 20, guard_dark)
    # Slight knobs at each end of the guard
    px(8, 24, guard_dark)
    px(14, 18, guard_hi)

    # Blade — long diagonal from (12, 20) up-right to (24, 8)
    blade_pts = [
        (12, 20), (13, 19), (14, 18), (15, 17), (16, 16), (17, 15),
        (18, 14), (19, 13), (20, 12), (21, 11), (22, 10), (23, 9), (24, 8),
    ]
    for (x, y) in blade_pts:
        # Spine (lower-right side of the diagonal)
        px(x + 1, y, bronze_dark)
        # Center body
        px(x, y, bronze)
        # Upper edge (highlight)
        px(x, y - 1, bronze_hi)
        # Outermost edge — bright steel sheen
        px(x - 1, y - 1, edge)
    # Pointed tip
    px(25, 7, bronze_hi)
    px(24, 7, edge)
    px(25, 8, bronze_dark)

    return img


def make_wooden_shield() -> Image.Image:
    """Round wooden shield viewed face-on, with horizontal plank seams and a
    central iron boss."""
    img = new_img()
    px, rect = helpers(img)
    ground_shadow(rect, 16, 27, 9)

    rim_dark = (50, 30, 15, 255)
    rim = (90, 55, 25, 255)
    wood_dark = (95, 60, 28, 255)
    wood = (150, 100, 55, 255)
    wood_hi = (200, 150, 95, 255)
    seam = (75, 45, 22, 255)
    iron_dark = (50, 50, 60, 255)
    iron = (115, 115, 130, 255)
    iron_hi = (200, 200, 215, 255)

    # Body — disc roughly centered on (16, 16), radius ~10
    rect(8, 8, 17, 17, wood)
    # Round off corners
    for (x, y) in [(8, 8), (24, 8), (8, 24), (24, 24)]:
        px(x, y, BG)
    for (x, y) in [(9, 8), (8, 9), (23, 8), (24, 9),
                   (9, 24), (8, 23), (23, 24), (24, 23),
                   (10, 7), (10, 25), (22, 7), (22, 25),
                   (7, 10), (25, 10), (7, 22), (25, 22)]:
        px(x, y, BG)
    # Outer rim
    for x in range(11, 22):
        px(x, 7, rim)
        px(x, 25, rim)
    for y in range(11, 22):
        px(7, y, rim)
        px(25, y, rim)
    # Rim corner pixels (rounded)
    for (x, y) in [(9, 9), (10, 8), (8, 10),
                   (22, 8), (23, 9), (24, 10),
                   (8, 22), (9, 23), (10, 24),
                   (22, 24), (23, 23), (24, 22)]:
        px(x, y, rim)
    # Rim shadow on the inside edge
    for (x, y) in [(11, 8), (12, 8), (20, 8), (21, 8),
                   (8, 11), (8, 12), (8, 20), (8, 21),
                   (24, 11), (24, 12), (24, 20), (24, 21),
                   (11, 24), (12, 24), (20, 24), (21, 24)]:
        px(x, y, rim_dark)

    # Plank seams — horizontal lines across the face
    for x in range(9, 24):
        if 9 <= x <= 23:
            px(x, 12, seam)
            px(x, 20, seam)

    # Plank highlights — upper-left of each plank
    for x in range(10, 23):
        if 9 <= x <= 23:
            px(x, 9, wood_hi)
            px(x, 13, wood_hi)
    # Plank shadows — lower-right
    for x in range(10, 23):
        if 9 <= x <= 23:
            px(x, 19, wood_dark)
            px(x, 23, wood_dark)

    # Wood grain flecks
    for (x, y) in [(11, 10), (14, 11), (18, 10), (21, 11),
                   (12, 15), (17, 16), (20, 14), (13, 17),
                   (11, 21), (15, 22), (20, 21), (18, 22)]:
        px(x, y, wood_dark)

    # Central iron boss — 5x5 rounded disc at (14..18, 14..18)
    rect(14, 14, 5, 5, iron)
    px(14, 14, BG); px(18, 14, BG)
    px(14, 18, BG); px(18, 18, BG)
    # Soften corners with mid tone
    px(14, 14, iron_dark)
    px(18, 14, iron_dark)
    px(14, 18, iron_dark)
    px(18, 18, iron_dark)
    # Highlight glint top-left
    px(15, 15, iron_hi)
    px(16, 15, iron_hi)
    px(15, 16, iron_hi)
    # Shadow bottom-right
    px(17, 17, iron_dark)
    px(17, 16, iron_dark)
    px(16, 17, iron_dark)
    # Boss outline
    for (x, y) in [(15, 14), (16, 14), (17, 14),
                   (14, 15), (14, 16), (14, 17),
                   (18, 15), (18, 16), (18, 17),
                   (15, 18), (16, 18), (17, 18)]:
        if img.getpixel((x, y))[3] == 0 or img.getpixel((x, y)) == iron:
            pass

    return img


def make_leather_armor() -> Image.Image:
    """Front-facing leather cuirass with shoulder guards, chest seam, and a
    cinched waist belt."""
    img = new_img()
    px, rect = helpers(img)
    ground_shadow(rect, 16, 27, 9)

    leather_dark = (70, 40, 20, 255)
    leather = (125, 80, 45, 255)
    leather_hi = (175, 125, 80, 255)
    seam = (60, 35, 18, 255)
    belt_dark = (40, 22, 10, 255)
    belt = (75, 45, 22, 255)
    buckle = (210, 175, 80, 255)
    buckle_hi = (245, 220, 130, 255)
    stitch = (200, 165, 110, 255)

    # Main torso block — slight hourglass: wide shoulders, narrow waist, flare
    # Top of torso (just below collar)
    rect(11, 10, 11, 2, leather)
    # Upper chest
    rect(10, 12, 13, 4, leather)
    # Mid (slightly narrower)
    rect(11, 16, 11, 3, leather)
    # Waist (narrowest)
    rect(11, 19, 11, 2, leather)
    # Skirt flare
    rect(10, 21, 13, 4, leather)

    # Shoulder pads (rounded protrusions at top corners)
    rect(8, 11, 3, 3, leather)
    rect(22, 11, 3, 3, leather)
    px(8, 11, BG); px(8, 13, leather_dark)
    px(24, 11, BG); px(24, 13, leather_dark)
    # Shoulder highlights
    px(9, 11, leather_hi)
    px(23, 11, leather_hi)
    px(9, 12, leather_hi)
    px(23, 12, leather_hi)

    # V-neck cutout at top center
    px(15, 10, BG)
    px(16, 10, BG)
    px(17, 10, BG)
    px(16, 11, BG)
    # Collar lip around neck
    px(14, 10, leather_dark)
    px(18, 10, leather_dark)
    px(15, 11, leather_dark)
    px(17, 11, leather_dark)

    # Top-light highlights across upper chest
    rect(11, 12, 11, 1, leather_hi)
    px(10, 13, leather_hi)
    px(22, 13, leather_hi)
    # Right-side shadow band
    rect(10, 15, 13, 1, leather_dark)

    # Chest seam down centerline
    for y in range(12, 19):
        px(16, y, seam)
    # Stitching dots flanking the seam
    for y in (13, 15, 17):
        px(15, y, stitch)
        px(17, y, stitch)

    # Side seams
    for y in range(12, 19):
        px(10, y, leather_dark)
        px(22, y, leather_dark)

    # Skirt highlights and shadow
    rect(10, 21, 13, 1, leather_hi)
    rect(10, 24, 13, 1, leather_dark)
    # Skirt seams
    for y in range(21, 25):
        px(14, y, seam)
        px(18, y, seam)

    # Waist belt
    rect(10, 19, 13, 2, belt)
    rect(10, 19, 13, 1, belt_dark)
    # Belt buckle
    rect(15, 19, 3, 2, buckle)
    px(15, 19, buckle_hi)
    px(16, 19, buckle_hi)
    px(17, 20, belt_dark)

    return img


def make_leather_helmet() -> Image.Image:
    """Domed leather cap viewed from the front, with a reinforced brow band
    and cheek-flap suggestions."""
    img = new_img()
    px, rect = helpers(img)
    ground_shadow(rect, 16, 25, 8)

    leather_dark = (75, 45, 22, 255)
    leather = (130, 85, 50, 255)
    leather_hi = (180, 130, 85, 255)
    band_dark = (50, 30, 15, 255)
    band = (90, 55, 28, 255)
    band_hi = (140, 95, 55, 255)
    stitch = (210, 175, 115, 255)

    # Dome — wider at the brim, narrower at the crown
    rect(12, 8, 9, 2, leather)         # crown band
    rect(11, 10, 11, 2, leather)       # upper dome
    rect(10, 12, 13, 4, leather)       # main dome
    rect(9, 16, 15, 2, leather)        # brim flare

    # Round off the crown corners
    px(12, 8, BG)
    px(20, 8, BG)
    px(11, 10, leather_dark)
    px(21, 10, leather_dark)
    # Round off the brim corners
    px(9, 17, leather_dark)
    px(23, 17, leather_dark)
    px(9, 16, BG)
    px(23, 16, BG)

    # Top-light highlight stripe across the upper-left of the dome
    rect(12, 8, 8, 1, leather_hi)
    rect(11, 10, 5, 1, leather_hi)
    px(10, 12, leather_hi)
    px(11, 12, leather_hi)
    px(12, 13, leather_hi)
    # Subtle right-side shadow
    rect(19, 12, 4, 1, leather_dark)
    px(22, 13, leather_dark)
    px(22, 14, leather_dark)
    px(22, 15, leather_dark)

    # Reinforced brow band — darker leather strap across the brim
    rect(10, 14, 13, 2, band)
    rect(10, 14, 13, 1, band_dark)
    rect(10, 15, 13, 1, band_hi)
    # Brow band rivets
    for x in (12, 15, 18, 21):
        px(x, 14, stitch)

    # Brim shadow underneath
    rect(10, 17, 13, 1, leather_dark)

    # Cheek-flap suggestion at lower sides
    px(9, 18, leather)
    px(10, 18, leather_dark)
    px(22, 18, leather_dark)
    px(23, 18, leather)
    px(9, 19, leather_dark)
    px(23, 19, leather_dark)

    return img


def make_leather_legs() -> Image.Image:
    """Pair of leather leggings viewed from the front, with a stitched seam
    down the centerline."""
    img = new_img()
    px, rect = helpers(img)
    ground_shadow(rect, 16, 27, 7)

    leather_dark = (65, 38, 18, 255)
    leather = (118, 76, 45, 255)
    leather_hi = (170, 120, 75, 255)
    belt_dark = (40, 22, 10, 255)
    belt = (80, 50, 25, 255)
    stitch = (200, 165, 110, 255)
    seam = (55, 30, 15, 255)

    # Waistband
    rect(10, 7, 13, 3, belt)
    rect(10, 7, 13, 1, belt_dark)
    rect(10, 9, 13, 1, belt_dark)
    # Buckle in center
    px(15, 8, stitch)
    px(16, 8, stitch)
    px(17, 8, stitch)

    # Hips (slightly wider than the legs)
    rect(10, 10, 13, 3, leather)

    # Crotch gap — narrow V at the top center
    px(16, 12, leather_dark)
    px(16, 13, BG)
    px(15, 13, leather)
    px(17, 13, leather)

    # Left leg
    rect(10, 13, 6, 13, leather)
    # Right leg
    rect(17, 13, 6, 13, leather)

    # Round the knees inward slightly
    px(10, 25, leather_dark)
    px(15, 25, leather_dark)
    px(17, 25, leather_dark)
    px(22, 25, leather_dark)

    # Inner seam (between legs)
    for y in range(13, 26):
        px(16, y, BG)

    # Top-light highlight down outer side of each leg
    for y in range(13, 25):
        px(10, y, leather_hi)
        px(17, y, leather_hi)
    # Shadow along inner side
    for y in range(13, 25):
        px(15, y, leather_dark)
        px(22, y, leather_dark)

    # Stitching down outer side of each leg
    for y in (15, 18, 21, 24):
        px(11, y, stitch)
        px(21, y, stitch)

    # Cuff at the bottom of each leg
    rect(10, 24, 6, 2, leather)
    rect(17, 24, 6, 2, leather)
    rect(10, 24, 6, 1, leather_dark)
    rect(17, 24, 6, 1, leather_dark)
    px(11, 25, leather_hi)
    px(18, 25, leather_hi)

    # Front seams down the thigh of each leg
    for y in range(13, 24):
        px(12, y, seam)
        px(20, y, seam)

    return img


def make_traveler_boots() -> Image.Image:
    """A pair of ankle boots, side-by-side, three-quarter side view with toes
    pointing right."""
    img = new_img()
    px, rect = helpers(img)
    ground_shadow(rect, 16, 26, 9)

    leather_dark = (45, 25, 12, 255)
    leather = (95, 60, 32, 255)
    leather_hi = (145, 100, 60, 255)
    sole_dark = (30, 18, 10, 255)
    sole = (60, 40, 22, 255)
    lace = (220, 190, 130, 255)
    cuff = (130, 90, 50, 255)
    cuff_hi = (180, 140, 90, 255)

    def boot(ox: int) -> None:
        # Shaft (ankle high)
        rect(ox + 2, 10, 5, 8, leather)
        # Cuff at top
        rect(ox + 2, 10, 5, 2, cuff)
        rect(ox + 2, 10, 5, 1, leather_dark)
        rect(ox + 2, 11, 5, 1, cuff_hi)
        # Heel/foot extends right
        rect(ox + 2, 18, 9, 4, leather)
        # Toe taper (front)
        rect(ox + 10, 19, 2, 2, leather)
        px(ox + 11, 18, BG)
        # Sole
        rect(ox + 2, 21, 10, 2, sole)
        rect(ox + 2, 21, 10, 1, sole_dark)
        # Heel notch
        rect(ox + 2, 22, 2, 1, sole_dark)
        # Top-light highlight along the front of the shaft
        for y in range(12, 18):
            px(ox + 2, y, leather_hi)
        # Side shadow along the back
        for y in range(12, 18):
            px(ox + 6, y, leather_dark)
        # Top of foot highlight
        rect(ox + 3, 18, 7, 1, leather_hi)
        # Bottom-of-foot shadow above the sole
        rect(ox + 3, 20, 7, 1, leather_dark)
        # Laces — three pale crosshatches
        for y in (12, 14, 16):
            px(ox + 3, y, lace)
            px(ox + 5, y, lace)
        # Tongue ridge
        for y in range(12, 17):
            px(ox + 4, y, leather_dark)

    boot(2)   # left boot
    boot(15)  # right boot

    return img


# ---------- ranged ---------- #


def make_bow() -> Image.Image:
    """Vertical shortbow — wooden limbs curving to the right, leather-wrapped
    grip in the middle, taut string running straight up the left side."""
    img = new_img()
    px, rect = helpers(img)
    ground_shadow(rect, 16, 28, 5)

    wood_dark = (75, 45, 22, 255)
    wood = (140, 95, 50, 255)
    wood_hi = (200, 150, 90, 255)
    grip_dark = (45, 25, 12, 255)
    grip = (90, 55, 28, 255)
    nock = (55, 35, 18, 255)
    string = (240, 230, 200, 255)

    # Bow limb curve (x position by y), bowing to the right.
    bow_col_by_y = {
        3: 16, 4: 15, 5: 15, 6: 16, 7: 17, 8: 18, 9: 18,
        10: 19, 11: 19, 12: 19,
        13: 18, 14: 17, 15: 17,
        16: 17, 17: 17,
        18: 17, 19: 17, 20: 18,
        21: 19, 22: 19, 23: 19,
        24: 18, 25: 17, 26: 16, 27: 15, 28: 15,
    }
    for y, x in bow_col_by_y.items():
        px(x - 1, y, wood_dark)
        px(x, y, wood)
        px(x + 1, y, wood_hi)

    # Nocks at tip and tail
    px(15, 2, nock)
    px(16, 2, nock)
    px(15, 29, nock)
    px(16, 29, nock)

    # Bowstring — straight line down the left side, from nock to nock
    for y in range(3, 29):
        px(14, y, string)

    # Leather grip wrap in the middle (covers limbs from y=14 to y=18)
    rect(16, 14, 3, 5, grip)
    rect(16, 14, 3, 1, grip_dark)
    rect(16, 18, 3, 1, grip_dark)
    # Grip wrap stripes
    for y in (15, 17):
        px(16, y, grip_dark)
        px(18, y, grip_dark)

    return img


def make_crossbow() -> Image.Image:
    """Horizontal crossbow with stock (butt at right), curved metal prod at
    the front (left), bowstring across the prod tips, and a small trigger
    guard underneath."""
    img = new_img()
    px, rect = helpers(img)
    ground_shadow(rect, 16, 26, 10)

    stock_dark = (60, 38, 18, 255)
    stock = (115, 75, 38, 255)
    stock_hi = (170, 125, 75, 255)
    metal_dark = (55, 55, 65, 255)
    metal = (125, 125, 140, 255)
    metal_hi = (200, 200, 215, 255)
    string = (240, 230, 200, 255)
    trigger = (150, 110, 50, 255)

    # Stock — horizontal beam from left (front) to right (butt)
    rect(8, 15, 17, 4, stock)
    rect(8, 15, 17, 1, stock_hi)
    rect(8, 18, 17, 1, stock_dark)

    # Butt taper at the right end (rounded shoulder)
    px(25, 15, BG)
    px(25, 18, BG)
    px(24, 15, stock_dark)
    px(24, 18, stock_dark)
    # Butt cap
    rect(25, 16, 2, 2, stock)
    px(26, 16, stock_dark)
    px(26, 17, stock_dark)

    # Front cap (metal collar where the prod mounts)
    rect(7, 14, 2, 6, metal_dark)
    rect(8, 14, 1, 6, metal)
    px(8, 14, metal_hi)

    # Prod (the bow arms) — curved arc mounted at the front,
    # tips reaching up to ~y=9 and down to ~y=24
    prod_pts_top = [
        (8, 13), (7, 12), (6, 11), (5, 10),
        (5, 9), (6, 8), (7, 8), (8, 8), (9, 9),
    ]
    prod_pts_bot = [
        (8, 20), (7, 21), (6, 22), (5, 23),
        (5, 24), (6, 25), (7, 25), (8, 25), (9, 24),
    ]
    for (x, y) in prod_pts_top + prod_pts_bot:
        px(x, y, metal)
        px(x, y - 1 if (x, y) in prod_pts_top else y + 1, metal_hi)
        px(x + 1, y, metal_dark)

    # Bowstring — drawn taut from prod tip to prod tip, hooked over the trigger
    # Top half: from (6, 8) diagonally down to (16, 16)
    for y in range(9, 17):
        x = 6 + (y - 9)
        px(x, y, string)
    # Bottom half: from (16, 17) diagonally down to (6, 25)
    for y in range(17, 26):
        x = 6 + (25 - y)
        px(x, y, string)
    # Hook over the trigger nut
    px(16, 16, string)
    px(16, 17, string)

    # Bolt groove down the top of the stock
    for x in range(10, 24):
        px(x, 15, stock_dark)
    # Bolt sitting in the groove (visible nub)
    rect(11, 14, 4, 1, metal_hi)
    px(15, 14, metal)

    # Trigger guard
    rect(15, 19, 5, 2, stock_dark)
    px(15, 21, stock_dark)
    px(19, 21, stock_dark)
    # Trigger lever
    px(17, 21, trigger)
    px(18, 21, trigger)
    px(17, 22, trigger)

    return img


# ---------- driver ---------- #


def main() -> None:
    out_root = os.path.join("assets", "overworld_objects")
    targets = [
        ("bronze_sword",   make_bronze_sword),
        ("wooden_shield",  make_wooden_shield),
        ("leather_armor",  make_leather_armor),
        ("leather_helmet", make_leather_helmet),
        ("leather_legs",   make_leather_legs),
        ("traveler_boots", make_traveler_boots),
        ("bow",            make_bow),
        ("crossbow",       make_crossbow),
    ]
    for type_id, maker in targets:
        out_dir = os.path.join(out_root, type_id)
        os.makedirs(out_dir, exist_ok=True)
        img = maker()
        path = os.path.join(out_dir, "sprite.png")
        img.save(path)
        print(f"Saved {path}")


if __name__ == "__main__":
    main()
